/**
 * Orion API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core';
import {
  HttpClient, HttpHeaders, HttpParams,
  HttpResponse, HttpEvent, HttpContext
} from '@angular/common/http';
import { Observable } from 'rxjs';
import { OpenApiHttpParams, QueryParamStyle } from '../query.params';

// @ts-ignore
import { ArticleDetailResponseDto } from '../model/articleDetailResponseDto';
// @ts-ignore
import { ArticlePageResponseDto } from '../model/articlePageResponseDto';
// @ts-ignore
import { CommentPageResponseDto } from '../model/commentPageResponseDto';
// @ts-ignore
import { CommentResponseDto } from '../model/commentResponseDto';
// @ts-ignore
import { CreateArticleRequestDto } from '../model/createArticleRequestDto';
// @ts-ignore
import { CreateCommentRequestDto } from '../model/createCommentRequestDto';
// @ts-ignore
import { ProblemDetail } from '../model/problemDetail';
// @ts-ignore
import { ValidationProblemDetail } from '../model/validationProblemDetail';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS } from '../variables';
import { Configuration } from '../configuration';
import { BaseService } from '../api.base.service';



@Injectable({
  providedIn: 'root'
})
export class ArticlesService extends BaseService {

  constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string | string[], @Optional() configuration?: Configuration) {
    super(basePath, configuration);
  }

  /**
   * Publier un article
   * @endpoint post /articles
   * @param createArticleRequestDto
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public createArticle(createArticleRequestDto: CreateArticleRequestDto, observe?: 'body', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean }): Observable<ArticleDetailResponseDto>;
  public createArticle(createArticleRequestDto: CreateArticleRequestDto, observe?: 'response', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean }): Observable<HttpResponse<ArticleDetailResponseDto>>;
  public createArticle(createArticleRequestDto: CreateArticleRequestDto, observe?: 'events', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean }): Observable<HttpEvent<ArticleDetailResponseDto>>;
  public createArticle(createArticleRequestDto: CreateArticleRequestDto, observe: any = 'body', reportProgress: boolean = false, options?: { httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean }): Observable<any> {
    if (createArticleRequestDto === null || createArticleRequestDto === undefined) {
      throw new Error('Required parameter createArticleRequestDto was null or undefined when calling createArticle.');
    }

    let localVarHeaders = this.defaultHeaders;

    // authentication (bearerAuth) required
    localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

    const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
      'application/json',
      'application/problem+json'
    ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;


    // to determine the Content-Type header
    const consumes: string[] = [
      'application/json'
    ];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
    }

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/articles`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<ArticleDetailResponseDto>('post', `${basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        body: createArticleRequestDto,
        responseType: <any>responseType_,
        ...(withCredentials ? { withCredentials } : {}),
        headers: localVarHeaders,
        observe: observe,
        ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
        reportProgress: reportProgress
      }
    );
  }

  /**
   * Ajouter un commentaire
   * @endpoint post /articles/{articleId}/comments
   * @param articleId
   * @param createCommentRequestDto
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public createComment(articleId: string, createCommentRequestDto: CreateCommentRequestDto, observe?: 'body', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean }): Observable<CommentResponseDto>;
  public createComment(articleId: string, createCommentRequestDto: CreateCommentRequestDto, observe?: 'response', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean }): Observable<HttpResponse<CommentResponseDto>>;
  public createComment(articleId: string, createCommentRequestDto: CreateCommentRequestDto, observe?: 'events', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean }): Observable<HttpEvent<CommentResponseDto>>;
  public createComment(articleId: string, createCommentRequestDto: CreateCommentRequestDto, observe: any = 'body', reportProgress: boolean = false, options?: { httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean }): Observable<any> {
    if (articleId === null || articleId === undefined) {
      throw new Error('Required parameter articleId was null or undefined when calling createComment.');
    }
    if (createCommentRequestDto === null || createCommentRequestDto === undefined) {
      throw new Error('Required parameter createCommentRequestDto was null or undefined when calling createComment.');
    }

    let localVarHeaders = this.defaultHeaders;

    // authentication (bearerAuth) required
    localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

    const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
      'application/json',
      'application/problem+json'
    ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;


    // to determine the Content-Type header
    const consumes: string[] = [
      'application/json'
    ];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
    }

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/articles/${this.configuration.encodeParam({ name: "articleId", value: articleId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: "uuid" })}/comments`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<CommentResponseDto>('post', `${basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        body: createCommentRequestDto,
        responseType: <any>responseType_,
        ...(withCredentials ? { withCredentials } : {}),
        headers: localVarHeaders,
        observe: observe,
        ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
        reportProgress: reportProgress
      }
    );
  }

  /**
   * Supprimer un article
   * Autorisé uniquement pour l\&#39;auteur de l\&#39;article ou un administrateur.
   * @endpoint delete /articles/{articleId}
   * @param articleId
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public deleteArticle(articleId: string, observe?: 'body', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/problem+json', context?: HttpContext, transferCache?: boolean }): Observable<any>;
  public deleteArticle(articleId: string, observe?: 'response', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/problem+json', context?: HttpContext, transferCache?: boolean }): Observable<HttpResponse<any>>;
  public deleteArticle(articleId: string, observe?: 'events', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/problem+json', context?: HttpContext, transferCache?: boolean }): Observable<HttpEvent<any>>;
  public deleteArticle(articleId: string, observe: any = 'body', reportProgress: boolean = false, options?: { httpHeaderAccept?: 'application/problem+json', context?: HttpContext, transferCache?: boolean }): Observable<any> {
    if (articleId === null || articleId === undefined) {
      throw new Error('Required parameter articleId was null or undefined when calling deleteArticle.');
    }

    let localVarHeaders = this.defaultHeaders;

    // authentication (bearerAuth) required
    localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

    const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
      'application/problem+json'
    ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;


    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/articles/${this.configuration.encodeParam({ name: "articleId", value: articleId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: "uuid" })}`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<any>('delete', `${basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        responseType: <any>responseType_,
        ...(withCredentials ? { withCredentials } : {}),
        headers: localVarHeaders,
        observe: observe,
        ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
        reportProgress: reportProgress
      }
    );
  }

  /**
   * Consulter un article
   * @endpoint get /articles/{articleId}
   * @param articleId
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public getArticleById(articleId: string, observe?: 'body', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean }): Observable<ArticleDetailResponseDto>;
  public getArticleById(articleId: string, observe?: 'response', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean }): Observable<HttpResponse<ArticleDetailResponseDto>>;
  public getArticleById(articleId: string, observe?: 'events', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean }): Observable<HttpEvent<ArticleDetailResponseDto>>;
  public getArticleById(articleId: string, observe: any = 'body', reportProgress: boolean = false, options?: { httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean }): Observable<any> {
    if (articleId === null || articleId === undefined) {
      throw new Error('Required parameter articleId was null or undefined when calling getArticleById.');
    }

    let localVarHeaders = this.defaultHeaders;

    // authentication (bearerAuth) required
    localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

    const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
      'application/json',
      'application/problem+json'
    ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;


    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/articles/${this.configuration.encodeParam({ name: "articleId", value: articleId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: "uuid" })}`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<ArticleDetailResponseDto>('get', `${basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        responseType: <any>responseType_,
        ...(withCredentials ? { withCredentials } : {}),
        headers: localVarHeaders,
        observe: observe,
        ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
        reportProgress: reportProgress
      }
    );
  }

  /**
   * Lister les commentaires d\&#39;un article
   * @endpoint get /articles/{articleId}/comments
   * @param articleId
   * @param page
   * @param size
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public getArticleComments(articleId: string, page?: number, size?: number, observe?: 'body', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean }): Observable<CommentPageResponseDto>;
  public getArticleComments(articleId: string, page?: number, size?: number, observe?: 'response', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean }): Observable<HttpResponse<CommentPageResponseDto>>;
  public getArticleComments(articleId: string, page?: number, size?: number, observe?: 'events', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean }): Observable<HttpEvent<CommentPageResponseDto>>;
  public getArticleComments(articleId: string, page?: number, size?: number, observe: any = 'body', reportProgress: boolean = false, options?: { httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean }): Observable<any> {
    if (articleId === null || articleId === undefined) {
      throw new Error('Required parameter articleId was null or undefined when calling getArticleComments.');
    }

    let localVarQueryParameters = new OpenApiHttpParams(this.encoder);

    localVarQueryParameters = this.addToHttpParams(
      localVarQueryParameters,
      'page',
      <any>page,
      QueryParamStyle.Form,
      true,
    );


    localVarQueryParameters = this.addToHttpParams(
      localVarQueryParameters,
      'size',
      <any>size,
      QueryParamStyle.Form,
      true,
    );


    let localVarHeaders = this.defaultHeaders;

    // authentication (bearerAuth) required
    localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

    const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
      'application/json',
      'application/problem+json'
    ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;


    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/articles/${this.configuration.encodeParam({ name: "articleId", value: articleId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: "uuid" })}/comments`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<CommentPageResponseDto>('get', `${basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        params: localVarQueryParameters.toHttpParams(),
        responseType: <any>responseType_,
        ...(withCredentials ? { withCredentials } : {}),
        headers: localVarHeaders,
        observe: observe,
        ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
        reportProgress: reportProgress
      }
    );
  }

  /**
   * Consulter son fil d\&#39;actualité
   * Retourne les articles des thèmes suivis par l\&#39;utilisateur connecté.
   * @endpoint get /articles
   * @param sort
   * @param page
   * @param size
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public getSubscribedArticles(sort?: 'newest' | 'oldest', page?: number, size?: number, observe?: 'body', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean }): Observable<ArticlePageResponseDto>;
  public getSubscribedArticles(sort?: 'newest' | 'oldest', page?: number, size?: number, observe?: 'response', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean }): Observable<HttpResponse<ArticlePageResponseDto>>;
  public getSubscribedArticles(sort?: 'newest' | 'oldest', page?: number, size?: number, observe?: 'events', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean }): Observable<HttpEvent<ArticlePageResponseDto>>;
  public getSubscribedArticles(sort?: 'newest' | 'oldest', page?: number, size?: number, observe: any = 'body', reportProgress: boolean = false, options?: { httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean }): Observable<any> {

    let localVarQueryParameters = new OpenApiHttpParams(this.encoder);

    localVarQueryParameters = this.addToHttpParams(
      localVarQueryParameters,
      'sort',
      <any>sort,
      QueryParamStyle.Form,
      true,
    );


    localVarQueryParameters = this.addToHttpParams(
      localVarQueryParameters,
      'page',
      <any>page,
      QueryParamStyle.Form,
      true,
    );


    localVarQueryParameters = this.addToHttpParams(
      localVarQueryParameters,
      'size',
      <any>size,
      QueryParamStyle.Form,
      true,
    );


    let localVarHeaders = this.defaultHeaders;

    // authentication (bearerAuth) required
    localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

    const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
      'application/json',
      'application/problem+json'
    ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;


    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/articles`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<ArticlePageResponseDto>('get', `${basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        params: localVarQueryParameters.toHttpParams(),
        responseType: <any>responseType_,
        ...(withCredentials ? { withCredentials } : {}),
        headers: localVarHeaders,
        observe: observe,
        ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
        reportProgress: reportProgress
      }
    );
  }

}
