/**
 * Orion API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ArticleSummaryResponseDto } from './articleSummaryResponseDto';


export interface ArticlePageResponseDto { 
    content: Array<ArticleSummaryResponseDto>;
    page: number;
    size: number;
    totalElements: number;
    totalPages: number;
}

