/**
 * Orion API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuthorResponseDto } from './authorResponseDto';
import { TopicResponseDto } from './topicResponseDto';


export interface ArticleDetailResponseDto { 
    id: string;
    title: string;
    slug: string;
    excerpt?: string;
    author: AuthorResponseDto;
    topic: TopicResponseDto;
    createdAt: string;
    content: string;
    updatedAt: string;
    commentCount: number;
}

