/**
 * Orion API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuthorResponseDto } from './authorResponseDto';


export interface CommentResponseDto { 
    id: string;
    content: string;
    author: AuthorResponseDto;
    createdAt: string;
    updatedAt: string;
}

