/**
 * Orion API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CommentResponseDto } from './commentResponseDto';


export interface CommentPageResponseDto { 
    content: Array<CommentResponseDto>;
    page: number;
    size: number;
    totalElements: number;
    totalPages: number;
}

