/**
 * Orion API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserResponseDto } from './userResponseDto';


export interface LoginResponseDto { 
    /**
     * Jeton JWT à transmettre dans Authorization Bearer.
     */
    accessToken: string;
    tokenType: LoginResponseDto.TokenTypeEnum;
    user: UserResponseDto;
}
export namespace LoginResponseDto {
    export const TokenTypeEnum = {
        Bearer: 'Bearer',
    } as const;
    export type TokenTypeEnum = typeof TokenTypeEnum[keyof typeof TokenTypeEnum];
}


