/**
 * Orion API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateUserRequestDto { 
    username?: string;
    email?: string;
    /**
     * Obligatoire lors du changement de mot de passe.
     */
    currentPassword?: string;
    password?: string;
}

