/**
 * Orion API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TopicResponseDto } from './topicResponseDto';


export interface UserProfileResponseDto { 
    id: string;
    username: string;
    email: string;
    createdAt: string;
    updatedAt: string;
    subscriptions: Array<TopicResponseDto>;
}

