/**
 * Orion API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ValidationProblemDetail { 
    type: string;
    title: string;
    status: number;
    detail: string;
    instance: string;
    code?: string;
    errors: { [key: string]: string; };
}

