spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/orion}
    username: ${DB_USERNAME:orion}
    password: ${DB_PASSWORD:orion}
    driver-class-name: org.postgresql.Driver


app:
  cors:
    allowed-origins: http://localhost:4200
  security:
    jwt:
      issuer: orion-test
      access-token-ttl: PT3H5M
      key-id: orion-test-key
      secret: MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=